budget/urls.py
from django.urls import path
from .views import budget as budget_view, transactions as transactions_view

app_name = "budget"

urlpatterns = [
    path("", budget_view.dashboard, name="index"),
    path("transactions", transactions_view.index, name="transactions.index"),
    path("transactions/list", transactions_view.list, name="transactions.list"),
]

pybox/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('budget/', include('budget.urls')),
]

pybox/views.py
from inertia import render


def index(request):
    return render(request, "Home")

pybox/templates/base.html
{% load django_vite %}
<!DOCTYPE html>
<html class="h-full" className="antialiased">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Pybox{% endblock %}</title>
    {% vite_hmr_client %}

    <script type="module">
      import RefreshRuntime from "http://localhost:3000/static/@react-refresh";
      RefreshRuntime.injectIntoGlobalHook(window);
      window.$RefreshReg$ = () => {};
      window.$RefreshSig$ = () => (type) => type;
      window.__vite_plugin_react_preamble_installed__ = true;
    </script>

    {% vite_asset 'js/main.tsx' %}
  </head>

  <body class="h-full bg-gray-100">
    {% block inertia %}{% endblock %}
  </body>
</html>

pybox/templates/home.html
{% extends 'base.html' %} {% block content %}
<div class="flex flex-col items-center">
    <h1 class="text-4xl font-bold">Personal Finance</h1>
    <p class="mt-4 text-lg">A simple budgeting app</p>
</div>

<footer class="absolute bottom-0 left-40 bg-white">
    <div class="mx-auto max-w-7xl overflow-hidden px-6 py-20 sm:py-24 lg:px-8">
        <nav
            class="-mb-6 columns-2 sm:flex sm:justify-center sm:space-x-12"
            aria-label="Footer"
        >
            <div class="pb-6">
                <a
                    href="{% url 'home' %}"
                    class="text-sm leading-6 text-gray-600 hover:text-gray-900"
                    >Home</a
                >
            </div>
            <div class="pb-6">
                <a
                    href="{% url 'budget:index' %}"
                    class="text-sm leading-6 text-gray-600 hover:text-gray-900"
                    >Budget</a
                >
            </div>
        </nav>
    </div>
</footer>
{% endblock %}